aimrt:
  plugin:
    plugins:
      - name: iceoryx_plugin
        path: ${PLUGIN_INSTALL_DIR}/libaimrt_iceoryx_plugin.so
        options:
          node_name: rl_deploy 
  log:
    core_lvl: INFO 
    backends:
      - type: console

  channel:
    backends:
      - type: iceoryx

    pub_topics_options:
      - topic_name: "(.*)"
        enable_backends: [iceoryx]
    sub_topics_options:
      - topic_name: "(.*)"
        enable_backends: [iceoryx]
